version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:2.11.3'
    restart: unless-stopped
    ports:
      - '10080:80'
      - '10081:81'
      - '10443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

